server:
    port: 9001
    shutdown: graceful
    tomcat:
        connection-timeout: 2s  ## how much time to wait for client to connect
        keep-alive-timeout: 15s ## how long to keep connection open while waiting for new client 
        threads:
            max: 50 
            min-spare: 5

polar:
    greetings: welcome to the local book catalog !!!


spring:
    application: 
        name: catalog-service 
    lifecycle:
        timeout-per-shutdown-phase: 15s
    config:
        import: "optional:configserver:"
    cloud:
        config:
            uri: http://localhost:8888
            request-connect-timeout: 5000
            request-read-timeout: 5000
            fail-fast: true 
            retry:
                max-attempts: 6 
                initial-interval: 1000
                max-interval: 2000 
                multiplier: 1.1 
    datasource:
        username: user
        password: password 
        url: jdbc:postgresql://localhost:5432/polardb_catalog
        hikari:
            connection-timeout: 2000 
            maxium-pool-size: 5
    sql:
        init:
            mode: always