server:
  port: 8888 
  tomcat:
    connection-timeout: 2s 
    keep-alive-timeout: 15s 
    threads:
      max: 50 
      min-spare: 5

spring:
  application:
    name: config-service 
  
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PolarBookshop/config-repo
          default-label: main 
          timeout: 5   #time limit to establish connection with remote repository
          clone-on-start: true  ## the repo clone happens at startup, That’s why it’s better to fail fast at startup and investigate the issue right away.
          force-pull: true ## force pulling remote repository and discard any local changes